### ISSUE TITLE
Current 0.7 branch crashes on WEBHOOK_UPDATE event

### ISSUE THREAD

**Issue by brakhane** [SunDwarf/curious#46]
0.7.9 worked fine, the current 0.7 branch seems to crash when WEBHOOKS_UPDATE is received

```
2019-01-24 03:54:37,805 ERROR curious.client: Error decoding event WEBHOOKS_UPDATE with data {'guild_id': '312742719237914624', 'channel_id': '537808121335250955'}!
Traceback (most recent call last):
  File "/home/dennis/.local/share/virtualenvs/orisa-C9I4W0oe/lib/python3.7/site-packages/curious/core/client.py", line 600, in handle_dispatches
    await self.events.fire_event(item, gateway=ctx.gateway, client=self)
  File "/home/dennis/.local/share/virtualenvs/orisa-C9I4W0oe/lib/python3.7/site-packages/curious/core/event.py", line 278, in fire_event
    for handler in self.event_listeners.getall(event_name, []):
  File "multidict/_multidict.pyx", line 39, in multidict._multidict._Base.getall
TypeError: MultiDict keys should be either str or subclasses of str
2019-01-24 03:54:37,808 ERROR curious.events: Unhandled exception in handle_dispatches!
Traceback (most recent call last):
  File "/home/dennis/.local/share/virtualenvs/orisa-C9I4W0oe/lib/python3.7/site-packages/curious/core/event.py", line 159, in _safety_wrapper
    await func(*args, **kwargs)
  File "/home/dennis/.local/share/virtualenvs/orisa-C9I4W0oe/lib/python3.7/site-packages/curious/core/client.py", line 600, in handle_dispatches
    await self.events.fire_event(item, gateway=ctx.gateway, client=self)
  File "/home/dennis/.local/share/virtualenvs/orisa-C9I4W0oe/lib/python3.7/site-packages/curious/core/event.py", line 278, in fire_event
    for handler in self.event_listeners.getall(event_name, []):
  File "multidict/_multidict.pyx", line 39, in multidict._multidict._Base.getall
TypeError: MultiDict keys should be either str or subclasses of str
2019-01-24 03:54:37,912 INFO  curious.gateway:shard-0: The websocket has closed
```
After that, no discord events are handled, so the bot is basically offline

**Comment by Fuyukai** [comment]
There is literally nothing that should've changed between 0.7 master and 0.7.9 relating to this so I have no clue.

**Comment by brakhane** [comment]
Yeah, I also don't see any changes that could have resulted in this. I also noticed I confused INTEGRATIONS_UPDATE with WEBHOOKS_UPDATE. I'll try to reproduce, no luck so far though

**Comment by brakhane** [comment]
I haven't been able to reproduce the bug so far. I've now deployed the 0.7 branch back to live and will see if the bug reoccurs.

**Comment by brakhane** [comment]
Still not able to reproduce. I suggest marking it as "not reproducable" and closing it for now.

Might just have been a cosmic neutrino flipping a bit somewhere AFAIK.
